import { dark, tailwind } from '@theme-ui/presets'
export default {
  ...dark.colors,
  //   primary: `tomato`,
  //   secondary: tailwind.colors.blue[9],
  background: tailwind.colors.gray[8],
  backgroundLight: tailwind.colors.gray[7],
  shadeBlue: `#00269A`,
  shadePink: `#cc0074`,
  primaryLight: `#ffffc7`,
  //  textMuted: `#667488`,
  //  text: `#444`,
  grayDark: tailwind.colors.gray[9],
  //   dark: tailwind.colors.gray[7],
  //   muted: tailwind.colors.gray[5],
  light: tailwind.colors.gray[3],
  lightDarker: tailwind.colors.gray[4],
  grayLighter: `#232b38`,
  yellow: `yellow`,
}
